# Generated by Django 5.1 on 2024-12-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_header', models.TextField(blank=True, null=True)),
                ('welcome_background', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('welcome_btn_text', models.CharField(blank=True, max_length=255, null=True)),
                ('home_first_paragrapgh', models.TextField(blank=True, null=True)),
                ('first_paragrapgh_background', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
                ('roaya_paragraph', models.TextField(blank=True, null=True)),
                ('messages_paragraph', models.TextField(blank=True, null=True)),
                ('goals_paragraph', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_paragraph_title', models.CharField(blank=True, max_length=255, null=True)),
                ('first_paragraph', models.TextField(blank=True, null=True)),
                ('second_paragraph_title', models.CharField(blank=True, max_length=255, null=True)),
                ('second_paragraph', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhoUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=255, null=True)),
                ('main_subtitle', models.TextField(blank=True, null=True)),
                ('main_background', models.ImageField(blank=True, null=True, upload_to='backgrounds/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
