# Generated by Django 5.1 on 2024-12-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_homepagecontent_relationspage_siteconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationspage',
            name='first_paragrapgh_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='relationspage',
            name='second_paragrapgh_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
    ]
