# Generated by Django 5.2.6 on 2025-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_relationspage_first_paragrapgh_background_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='homepagecontent',
            options={'verbose_name': 'Home Page Content', 'verbose_name_plural': 'Home Page Content'},
        ),
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'verbose_name': 'Job Request', 'verbose_name_plural': 'Job Requests'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'verbose_name': 'Project Request', 'verbose_name_plural': 'Project Requests'},
        ),
        migrations.AlterModelOptions(
            name='relationspage',
            options={'verbose_name': 'Relations Page', 'verbose_name_plural': 'Relations Pages'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site Configuration', 'verbose_name_plural': 'Site Configuration'},
        ),
        migrations.AlterModelOptions(
            name='whouspage',
            options={'verbose_name': 'Who Us Page', 'verbose_name_plural': 'Who Us Pages'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='first_paragrapgh_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='First Paragraph Background'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='goals_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Goals Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='home_first_paragrapgh',
            field=models.TextField(blank=True, null=True, verbose_name='First Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='messages_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Messages Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='roaya_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Vision Paragraph'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='welcome_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Welcome Background'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='welcome_btn_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Welcome Button Text'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='welcome_header',
            field=models.TextField(blank=True, null=True, verbose_name='Welcome Header'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='CV/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='field',
            field=models.CharField(max_length=50, verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='project_file',
            field=models.ImageField(blank=True, null=True, upload_to='reports/', verbose_name='Project File'),
        ),
        migrations.AlterField(
            model_name='relationspage',
            name='first_paragrapgh_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='First Paragraph Background'),
        ),
        migrations.AlterField(
            model_name='relationspage',
            name='first_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='First Paragraph'),
        ),
        migrations.AlterField(
            model_name='relationspage',
            name='first_paragraph_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Paragraph Title'),
        ),
        migrations.AlterField(
            model_name='relationspage',
            name='second_paragrapgh_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Second Paragraph Background'),
        ),
        migrations.AlterField(
            model_name='relationspage',
            name='second_paragraph',
            field=models.TextField(blank=True, null=True, verbose_name='Second Paragraph'),
        ),
        migrations.AlterField(
            model_name='relationspage',
            name='second_paragraph_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Second Paragraph Title'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False, verbose_name='Maintenance Mode'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='My Site', max_length=255, verbose_name='Site Name'),
        ),
        migrations.AlterField(
            model_name='whouspage',
            name='main_background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Main Background'),
        ),
        migrations.AlterField(
            model_name='whouspage',
            name='main_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Main Subtitle'),
        ),
        migrations.AlterField(
            model_name='whouspage',
            name='main_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Main Title'),
        ),
    ]
