# Generated by Django 5.2.7 on 2026-01-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_contact_options_alter_homepagecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Report year (e.g., 2024)', unique=True, verbose_name='Year')),
                ('title', models.CharField(help_text='Report title (e.g., التقرير السنوي 2024)', max_length=255, verbose_name='Title')),
                ('pdf_file', models.FileField(help_text='Upload the report PDF file', upload_to='reports/', verbose_name='PDF File')),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Show this report on the website', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-year'],
            },
        ),
    ]
