# Generated by Django 6.0.1 on 2026-01-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='The question that users might ask', verbose_name='Question')),
                ('answer', models.TextField(help_text='The answer to the question', verbose_name='Answer')),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for better matching (optional)', max_length=500, verbose_name='Keywords')),
                ('category', models.CharField(blank=True, help_text='Category for organizing questions (e.g., Services, About Us)', max_length=100, null=True, verbose_name='Category')),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers first)', verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, help_text='Show this Q&A in the chatbot', verbose_name='Active')),
                ('view_count', models.IntegerField(default=0, help_text='Number of times this answer was shown', verbose_name='View Count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Chatbot Q&A',
                'verbose_name_plural': 'Chatbot Q&As',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
