# -*- coding: utf-8 -*-
"""
Django settings for real_state project.

Generated by 'django-admin startproject' using Django 5.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from django.contrib.messages import constants as messages
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-#t@cz^0twpq8l8txtm!w9h%%)oxeyz%+2s_b$)x!ui&7a5o-+k"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main",
    "crispy_forms",
    "crispy_bootstrap5",
    "constance",
    "constance.backends.database",
    "rosetta",
]

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

# Crispy Forms Configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # Enable localization
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",  # X_FRAME_OPTIONS below
    "main.middleware.ForceArabicDefaultMiddleware",  # force Arabic
]

ROOT_URLCONF = "real_state.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "constance.context_processors.config",
            ],
        },
    },
]

WSGI_APPLICATION = "real_state.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = "ar"  # Default language Arabic
TIME_ZONE = "Asia/Riyadh"  # Saudi Arabia timezone

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Available languages
LANGUAGES = [
    ("ar", _("Arabic")),
    ("en", _("English")),
]

# Path for locale translations
LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
DEFAULT_STATIC_FOLDER_NAME = os.environ.get(
    "DEFAULT_STATIC_FOLDER_NAME",
    default="static",
)
STATIC_URL = f"/{DEFAULT_STATIC_FOLDER_NAME}/"
STATIC_ROOT = str(BASE_DIR / "staticfiles")  # Directory for collectstatic
STATICFILES_DIRS = [str(BASE_DIR / "static")]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]


# Media files
DEFAULT_MEDIA_FOLDER_NAME = os.environ.get("DEFAULT_MEDIA_FOLDER_NAME", default="media")
MEDIA_ROOT = str(BASE_DIR / DEFAULT_MEDIA_FOLDER_NAME)
MEDIA_URL = f"/{DEFAULT_MEDIA_FOLDER_NAME}/"


# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Allow same-origin iframes (for PDF preview in reports)
X_FRAME_OPTIONS = "SAMEORIGIN"


# Messages style
MESSAGE_TAGS = {
    messages.DEBUG: "alert-secondary",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}


# Authentication redirects
LOGIN_URL = "login/"
LOGIN_REDIRECT_URL = "contacts/"
LOGOUT_REDIRECT_URL = "login/"


# Constance dynamic settings
CONSTANCE_CONFIG = {
    "COMPANY_NAME": ("ثمار", "اسم الشركة"),
    "PHONE_NUMBER": ("0591616638", "رقم الهاتف"),
    "CONTACT_EMAIL": ("info@thimar.com.sa", "البريد الإلكتروني"),
    "FACEBOOK_URL": ("#", "رابط فيسبوك"),
    "TWITTER_URL": ("#", "رابط تويتر"),
    "INSTAGRAM_URL": ("#", "رابط انستقرام"),
    "LINKEDIN_URL": ("#", "رابط لينكدإن"),
    "YOUTUBE_URL": ("#", "رابط يوتيوب"),
    "ADDRESS": ("الرياض، المملكة العربية السعودية", "عنوان الشركة"),
    "ADS_LINK": ("http://google/.com", "رابط الأعلان"),
    "ADS_TITLE": ("رابط  الأعلان", "عنوان الأعلان"),
    "GOOGLE_MAPS_EMBED_URL": (
        "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3624.5347686765!2d46.67175431495965!3d24.71359998410654!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e2f03c3cda885c7%3A0x6d2c5acb88d39f3f!2sRiyadh%2C%20Saudi%20Arabia!5e0!3m2!1sen!2s!4v1234567890123!5m2!1sen!2s",
        "رابط خريطة جوجل (Google Maps Embed URL)",
    ),
    "GOOGLE_TAG_MANAGER_ID": ("", "Google Tag Manager ID (GTM-XXXXXXX)"),
    "GOOGLE_ANALYTICS_ID": ("", "Google Analytics ID (G-XXXXXXXXXX or UA-XXXXXXXXX-X)"),
    "GOOGLE_ADS_CONVERSION_ID": ("", "Google Ads Conversion ID (AW-XXXXXXXXX)"),
    "GOOGLE_ADS_CONVERSION_LABEL": ("", "Google Ads Conversion Label"),
}
LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]
# Rosetta Configuration
ROSETTA_MESSAGES_PER_PAGE = 50
ROSETTA_ENABLE_TRANSLATION_SUGGESTIONS = True
ROSETTA_MESSAGES_SOURCE_LANGUAGE_CODE = "ar"
ROSETTA_MESSAGES_SOURCE_LANGUAGE_NAME = "Arabic"
ROSETTA_SHOW_AT_ADMIN_PANEL = True
ROSETTA_REQUIRES_AUTH = True  # Only authenticated users can access
